import type { MotifIconKey } from "feature/guilds/data/guildCosmetics";
import type { IconType } from "react-icons";
import {
  GiAnarchy,
  GiAnchor,
  GiAngelWings,
  GiAnvil,
  GiAudioCassette,
  GiBat,
  GiBattleAxe,
  GiBearHead,
  GiBeerHorn,
  GiBeerStein,
  GiBlackKnightHelm,
  GiBroadsword,
  GiBull,
  GiBullseye,
  GiBurningSkull,
  GiCampfire,
  GiCandleFlame,
  GiCastle,
  GiCat,
  GiCoffeeMug,
  GiCometSpark,
  GiCompass,
  GiCrossedAxes,
  GiCrossedBones,
  GiCrossedSwords,
  GiCrown,
  GiCrystalBall,
  GiDaggerRose,
  GiDeathSkull,
  GiDevilMask,
  GiDragonHead,
  GiDrum,
  GiDrumKit,
  GiEagleEmblem,
  GiFist,
  GiFlame,
  GiGears,
  GiGhost,
  GiGrimReaper,
  GiGuitar,
  GiGuitarBassHead,
  GiGuitarHead,
  GiHangingSpider,
  GiHeadphones,
  GiHeartWings,
  GiHeraldicSun,
  GiHornedHelm,
  GiHuntingHorn,
  GiImperialCrown,
  GiLaurelCrown,
  GiLaurelsTrophy,
  GiLightningStorm,
  GiLightningTrio,
  GiLion,
  GiMagicPotion,
  GiMetalDisc,
  GiMetalHand,
  GiMicrophone,
  GiMoon,
  GiMusicalKeyboard,
  GiMusicalNotes,
  GiMusicalScore,
  GiNinjaStar,
  GiOctopus,
  GiOldMicrophone,
  GiOwl,
  GiPianoKeys,
  GiPirateFlag,
  GiPirateSkull,
  GiRaven,
  GiRobotHelmet,
  GiRocket,
  GiRollingDices,
  GiSamuraiHelmet,
  GiScorpion,
  GiSevenPointedStar,
  GiSharkJaws,
  GiShield,
  GiSkeletonKey,
  GiSkullCrossedBones,
  GiSnake,
  GiSpartanHelmet,
  GiSpeaker,
  GiSpiderWeb,
  GiThorHammer,
  GiTigerHead,
  GiTrombone,
  GiUnlitBomb,
  GiVerticalBanner,
  GiVikingHelmet,
  GiWarhammer,
  GiWerewolf,
  GiWingedEmblem,
  GiWolfHead,
  GiWolfHowl,
} from "react-icons/gi";

/**
 * Which drawing each motif key means. Client-side only: the catalog and the
 * server deal in keys, and this is the one place a key becomes a component.
 *
 * All Game Icons, deliberately. They are solid glyphs drawn in one hand, so
 * any four of them sit together on a banner the way four lucide outlines and
 * four filled emblems mixed would not.
 */
export const MOTIF_ICON_COMPONENTS: Record<MotifIconKey, IconType> = {
  guitar: GiGuitar,
  bass: GiGuitarBassHead,
  headstock: GiGuitarHead,
  notes: GiMusicalNotes,
  score: GiMusicalScore,
  mic: GiMicrophone,
  oldmic: GiOldMicrophone,
  speaker: GiSpeaker,
  headphones: GiHeadphones,
  drum: GiDrum,
  drumkit: GiDrumKit,
  piano: GiPianoKeys,
  keyboard: GiMusicalKeyboard,
  trombone: GiTrombone,
  cassette: GiAudioCassette,
  vinyl: GiMetalDisc,
  horn: GiHuntingHorn,
  metalhand: GiMetalHand,

  skull: GiDeathSkull,
  crossbones: GiSkullCrossedBones,
  bones: GiCrossedBones,
  pirate: GiPirateSkull,
  burning: GiBurningSkull,
  dragon: GiDragonHead,
  wolf: GiWolfHead,
  howl: GiWolfHowl,
  werewolf: GiWerewolf,
  raven: GiRaven,
  eagle: GiEagleEmblem,
  lion: GiLion,
  tiger: GiTigerHead,
  bear: GiBearHead,
  bull: GiBull,
  snake: GiSnake,
  spider: GiHangingSpider,
  web: GiSpiderWeb,
  bat: GiBat,
  owl: GiOwl,
  cat: GiCat,
  shark: GiSharkJaws,
  octopus: GiOctopus,
  scorpion: GiScorpion,
  reaper: GiGrimReaper,
  ghost: GiGhost,
  devil: GiDevilMask,
  robot: GiRobotHelmet,

  crown: GiCrown,
  imperial: GiImperialCrown,
  laurel: GiLaurelCrown,
  swords: GiCrossedSwords,
  sword: GiBroadsword,
  axes: GiCrossedAxes,
  battleaxe: GiBattleAxe,
  hammer: GiThorHammer,
  warhammer: GiWarhammer,
  shield: GiShield,
  spartan: GiSpartanHelmet,
  viking: GiVikingHelmet,
  knight: GiBlackKnightHelm,
  samurai: GiSamuraiHelmet,
  hornedhelm: GiHornedHelm,
  castle: GiCastle,
  banner: GiVerticalBanner,
  pirateflag: GiPirateFlag,
  fist: GiFist,
  anarchy: GiAnarchy,
  wings: GiWingedEmblem,
  angelwings: GiAngelWings,
  bullseye: GiBullseye,
  bomb: GiUnlitBomb,
  key: GiSkeletonKey,

  flame: GiFlame,
  candle: GiCandleFlame,
  campfire: GiCampfire,
  lightning: GiLightningTrio,
  storm: GiLightningStorm,
  sun: GiHeraldicSun,
  moon: GiMoon,
  star: GiSevenPointedStar,
  shuriken: GiNinjaStar,
  comet: GiCometSpark,
  crystal: GiCrystalBall,
  potion: GiMagicPotion,

  heart: GiHeartWings,
  rose: GiDaggerRose,
  beer: GiBeerStein,
  drinkinghorn: GiBeerHorn,
  coffee: GiCoffeeMug,
  anvil: GiAnvil,
  gears: GiGears,
  dice: GiRollingDices,
  trophy: GiLaurelsTrophy,
  rocket: GiRocket,
  compass: GiCompass,
  anchor: GiAnchor,
};

export const motifComponents = (keys: readonly MotifIconKey[]): IconType[] =>
  keys.map((key) => MOTIF_ICON_COMPONENTS[key]);
