export type NavPagesTypes =
  | "profile"
  | "exercise"
  | "report"
  | "leadboard"
  | "leaderboard"
  | "faq"
  | "songs"
  | "library"
  | "guide"
  | "my_songs"
  | "seasons"
  | "timer"
  | "settings"
  | null;
