import AiCoachView from "feature/aiCoach/view/AiCoachView";
import { PremiumFeaturePreview } from "feature/premium/components/PremiumFeaturePreview";
import { PremiumGate } from "feature/premium/components/PremiumGate";
import { selectUserInfo } from "feature/user/store/userSlice";
import AppLayout from "layouts/AppLayout/AppLayout";
import { Compass, Map, Target, Zap } from "lucide-react";
import type { ReactElement } from "react";
import { useAppSelector } from "store/hooks";
import type { NextPageWithLayout } from "types/page";
import { withAuth } from "utils/auth/serverAuth";

const AiCoachPage: NextPageWithLayout = () => {
  const userInfo = useAppSelector(selectUserInfo);
  const isMaster = userInfo?.role === "master" || userInfo?.role === "admin";

  // Show premium preview for non-master users
  if (!isMaster && userInfo !== null) {
    return (
      <PremiumFeaturePreview
        eyebrow="Generate your path"
        title="Roadmap"
        description="Get a personalized learning roadmap generated by AI. Define your goals and receive a step-by-step practice plan designed specifically for your skill level and musical aspirations."
        features={[
          {
            icon: <Map className="h-5 w-5" />,
            label: "Personalized Roadmap",
            description: "AI-generated learning paths tailored to your musical goals",
          },
          {
            icon: <Target className="h-5 w-5" />,
            label: "Goal-Based Planning",
            description: "Set your goals and get a structured practice schedule",
          },
          {
            icon: <Compass className="h-5 w-5" />,
            label: "Skill Milestones",
            description: "Track progress with clear milestones and checkpoints",
          },
          {
            icon: <Zap className="h-5 w-5" />,
            label: "Adaptive Guidance",
            description: "Recommendations adjust based on your practice progress",
          },
        ]}
        availableIn="master"
      />
    );
  }

  return (
    <div className="bg-second-600 rounded overflow-visible flex flex-col border-none shadow-sm min-h-screen lg:mt-16">
      <PremiumGate feature="ai-coach" requiredPlan="master">
        <AiCoachView />
      </PremiumGate>
    </div>
  );
};

AiCoachPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <AppLayout
      pageId="ai-coach"
      subtitle="Roadmap"
      variant="secondary"
    >
      {page}
    </AppLayout>
  );
};

export default AiCoachPage;

export const getServerSideProps = withAuth({
  redirectIfUnauthenticated: "/login",
  translations: [
    "common",
    "profile",
    "footer",
    "achievements",
    "toast",
    "skills",
    "songs",
    "chat",
    "my_plans",
    "exercises",
  ],
});
