/**
 * Generated by `npm run update-hero-stats` — do not hand-edit the numbers.
 * Rerun the script (see scripts/updateHeroStats.test.ts) whenever the stats
 * feel stale; they don't need to be live, just occasionally refreshed.
 *
 * Last refreshed: 2026-07-23
 * Raw counts before rounding: users=2440, sessions=7638, hours=7029
 */
export const HERO_STATS = [
  { value: 2440, label: "guitarists on board" },
  { value: 7000, label: "hours practiced" },
  { value: 7600, label: "sessions logged" },
] as const;
