import { promises as fs } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

/**
 * Turns the vendored single-file metronome (marxd262/Metronome, used with the
 * author's permission) into something /tools/metronome can render server-side
 * inside a shadow root, instead of an iframe that search engines index as a
 * separate, contentless page.
 *
 * The upstream file assumes it owns the whole document, so:
 *  - CSS: `:root` / `body` selectors are re-pointed at `.rq-root`, the element
 *    standing in for <body> inside the shadow root. The shadow root keeps the
 *    stylesheet's cascade layers intact — dropped into the page as-is, Tailwind's
 *    unlayered preflight would beat every layered rule it has.
 *  - Markup: the title becomes an <h2>, so the page keeps a single <h1>.
 *  - JS: both <script> blocks are wrapped in mountMetronome(shadowRoot, rootEl),
 *    which returns a teardown. Document lookups go to the shadow root, document
 *    and window listeners are tracked for removal, event targets are read from
 *    composedPath() (at document level they are retargeted to the host), and the
 *    Space/arrow shortcuts only fire once the player has clicked into the
 *    metronome, so Space still scrolls the rest of the page.
 *
 * To update: replace src/feature/metronome/vendor/metronome.html with the new
 * upstream file, re-apply the colours in its `classic` theme block, then run
 * `node scripts/buildMetronome.mjs`.
 */

const __dirname = dirname(fileURLToPath(import.meta.url));
const FEATURE_DIR = join(__dirname, '../src/feature/metronome');
const SOURCE_PATH = join(FEATURE_DIR, 'vendor/metronome.html');
const OUTPUT_PATH = join(FEATURE_DIR, 'generated/metronomeApp.ts');

const take = (source, pattern, label) => {
  const match = source.match(pattern);
  if (!match) throw new Error(`buildMetronome: ${label} not found in ${SOURCE_PATH}`);
  return match[1];
};

/** Replaces every occurrence and fails loudly when the upstream code moved on. */
const replaceAll = (source, from, to, expected) => {
  const count = source.split(from).length - 1;
  if (count === 0 || (expected !== undefined && count !== expected)) {
    throw new Error(`buildMetronome: expected ${expected ?? '1+'} × "${from}", found ${count}`);
  }
  return source.split(from).join(to);
};

export const transformCss = (css) =>
  css
    // Comments first: several of them mention "body", which the rewrites below
    // would otherwise turn into nonsense.
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/:root(\[data-theme="[a-z-]+"\]) body/g, '.rq-root$1')
    .replace(/:root/g, '.rq-root')
    .replace(/\bbody\b/g, '.rq-root')
    .replace(/\bh1\b/g, 'h2')
    .replace(/\n\s*\n/g, '\n');

export const transformMarkup = (markup) =>
  markup
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<h1>/g, '<h2>')
    .replace(/<\/h1>/g, '</h2>')
    .replace(/\n\s*\n/g, '\n')
    .trim();

export const transformScript = (script) => {
  let out = script;
  out = replaceAll(out, 'document.getElementById(', '__root.getElementById(');
  out = replaceAll(out, 'document.querySelectorAll(', '__root.querySelectorAll(');
  out = replaceAll(out, 'document.querySelector(', '__root.querySelector(');
  out = replaceAll(out, 'document.activeElement', '(__root.activeElement || document.activeElement)');
  out = replaceAll(out, 'document.documentElement', '__el');
  out = replaceAll(out, 'document.body', '__el');
  out = replaceAll(out, 'document.addEventListener(', '__on(document, ');
  out = replaceAll(out, 'window.addEventListener(', '__on(window, ');
  out = replaceAll(out, 'e.target', '__target(e)');
  // The shortcut handler is the one keydown listener on document.
  out = replaceAll(out, '  if (!globalShortcutAllowed()) return;\n\n  if (e.code', '  if (!__active || !globalShortcutAllowed()) return;\n\n  if (e.code', 1);
  return out;
};

export const buildMetronome = (html) => {
  // Split on the real tags at the start of a line: comments in the stylesheet
  // mention "<script>" and "<header>" in passing.
  const bodyStart = html.indexOf('\n<body>');
  if (bodyStart === -1) throw new Error('buildMetronome: <body> not found');
  const head = html.slice(0, bodyStart);
  const body = html.slice(bodyStart);

  const css = transformCss(take(head, /\n<style>([\s\S]*)\n<\/style>/, '<style>'));
  const markup = transformMarkup(take(body, /<body>([\s\S]*?)\n<script>/, '<body> markup'));
  const scripts = [...body.matchAll(/\n<script>([\s\S]*?)\n<\/script>/g)].map((m) => m[1]);
  if (scripts.length !== 2) throw new Error(`buildMetronome: expected 2 <script> blocks, found ${scripts.length}`);
  const script = transformScript(scripts.join('\n'));

  return `// @ts-nocheck
/* eslint-disable */
// GENERATED by scripts/buildMetronome.mjs from src/feature/metronome/vendor/metronome.html.
// Do not edit by hand. Original: https://github.com/marxd262/Metronome (used with permission).

export const METRONOME_CSS = ${JSON.stringify(`:host { display: block; }\n${css}`)};

export const METRONOME_MARKUP = ${JSON.stringify(`<div class="rq-root" data-theme="classic">${markup}</div>`)};

export function mountMetronome(__root, __el) {
  const __listeners = [];
  const __on = (target, type, fn, options) => {
    target.addEventListener(type, fn, options);
    __listeners.push([target, type, fn, options]);
  };
  const __target = (e) => (e.composedPath ? e.composedPath()[0] : e.target);
  let __active = false;
  const __trackActive = (e) => { __active = e.composedPath().includes(__el); };
  __on(document, 'pointerdown', __trackActive, true);
  __on(document, 'focusin', __trackActive, true);

${script}

  return () => {
    stopPlayback();
    closeOpenQuickSelectPopup();
    if (audioCtx) audioCtx.close().catch(() => {});
    for (const [target, type, fn, options] of __listeners) target.removeEventListener(type, fn, options);
  };
}
`;
};

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const html = await fs.readFile(SOURCE_PATH, 'utf8');
  await fs.mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await fs.writeFile(OUTPUT_PATH, buildMetronome(html));
  console.log(`✓ Built metronome at ${OUTPUT_PATH}`);
}
