// @vitest-environment node

/**
 * Rerunnable script: computes the three landing-hero stats (guitarists on
 * board, hours practiced, sessions logged) from Firestore and writes them
 * into src/feature/landing/data/heroStats.ts. The hero reads that generated
 * file, so the landing page never queries Firestore itself.
 *
 * "sessions logged" / "hours practiced" come from the `logs` collection: every
 * completed practice report writes a doc there with a numeric
 * `timeSumary.sumTime` (ms). Other log kinds in that same collection (song
 * status changes, achievements, marketplace listings, recordings, ...) don't
 * have that field, so filtering on it (`>= 0`) selects only real sessions.
 * "guitarists on board" is just a count of the `users` collection.
 *
 * Numbers are rounded DOWN before being written (users to the nearest 10,
 * hours/sessions to the nearest 100) so the page never overstates reality
 * and small day-to-day drift doesn't require a rerun. Exact raw counts are
 * logged to the console and stamped as a comment in the generated file.
 *
 * Run with: npm run update-hero-stats
 * Guarded by `--mode hero-stats` so a plain `vitest`/`npm run test` skips it.
 */
import * as admin from "firebase-admin";
import fs from "fs";
import path from "path";
import { describe, it } from "vitest";

const OUTPUT_PATH = path.resolve(
  __dirname,
  "..",
  "src/feature/landing/data/heroStats.ts",
);

// Vitest only auto-loads .env files matching its mode, so fall back to the
// project env files Next.js uses in dev.
const readServiceAccountJson = (): string | undefined => {
  if (process.env.FIREBASE_SERVICE_ACCOUNT_JSON) {
    return process.env.FIREBASE_SERVICE_ACCOUNT_JSON;
  }
  for (const file of [".env.development.local", ".env.local", ".env"]) {
    const envPath = path.resolve(__dirname, "..", file);
    if (!fs.existsSync(envPath)) continue;
    for (const line of fs.readFileSync(envPath, "utf-8").split(/\r?\n/)) {
      if (!line.startsWith("FIREBASE_SERVICE_ACCOUNT_JSON=")) continue;
      let value = line.slice("FIREBASE_SERVICE_ACCOUNT_JSON=".length).trim();
      if (
        (value.startsWith("'") && value.endsWith("'")) ||
        (value.startsWith('"') && value.endsWith('"'))
      ) {
        value = value.slice(1, -1);
      }
      if (value) return value;
    }
  }
  return undefined;
};

const roundDown = (value: number, step: number) =>
  Math.floor(value / step) * step;

const isHeroStatsMode = (import.meta as any).env?.MODE === "hero-stats";

(isHeroStatsMode ? describe : describe.skip)("Update hero stats", () => {
  it(
    "computes real totals from Firestore and writes heroStats.ts",
    async () => {
      const serviceAccountJson = readServiceAccountJson();
      if (!serviceAccountJson) {
        throw new Error(
          "FIREBASE_SERVICE_ACCOUNT_JSON not found in process.env or project .env files",
        );
      }
      if (!admin.apps.length) {
        admin.initializeApp({
          credential: admin.credential.cert(JSON.parse(serviceAccountJson)),
        });
      }

      const firestore = admin.firestore();
      const { AggregateField } = admin.firestore;

      const usersCountSnap = await firestore.collection("users").count().get();
      const totalUsers = usersCountSnap.data().count;

      // Only docs written by a practice report carry `timeSumary.sumTime`;
      // every other log kind in this collection lacks that field entirely,
      // so this inequality filter doubles as an existence check.
      const sessionsQuery = firestore
        .collection("logs")
        .where("timeSumary.sumTime", ">=", 0);
      const sessionsAggSnap = await sessionsQuery
        .aggregate({
          sessionCount: AggregateField.count(),
          totalMs: AggregateField.sum("timeSumary.sumTime"),
        })
        .get();
      const { sessionCount, totalMs } = sessionsAggSnap.data();
      const totalHours = totalMs / (1000 * 60 * 60);

      const rounded = {
        guitaristsOnBoard: roundDown(totalUsers, 10),
        hoursPracticed: roundDown(totalHours, 100),
        sessionsLogged: roundDown(sessionCount, 100),
      };

      console.log("[update-hero-stats] raw:", {
        totalUsers,
        sessionCount,
        totalHours: Math.round(totalHours),
      });
      console.log("[update-hero-stats] rounded (written to file):", rounded);

      const fileContent = `/**
 * Generated by \`npm run update-hero-stats\` — do not hand-edit the numbers.
 * Rerun the script (see scripts/updateHeroStats.test.ts) whenever the stats
 * feel stale; they don't need to be live, just occasionally refreshed.
 *
 * Last refreshed: ${new Date().toISOString().slice(0, 10)}
 * Raw counts before rounding: users=${totalUsers}, sessions=${sessionCount}, hours=${Math.round(totalHours)}
 */
export const HERO_STATS = [
  { value: ${rounded.guitaristsOnBoard}, label: "guitarists on board" },
  { value: ${rounded.hoursPracticed}, label: "hours practiced" },
  { value: ${rounded.sessionsLogged}, label: "sessions logged" },
] as const;
`;

      fs.writeFileSync(OUTPUT_PATH, fileContent);
      console.log(`[update-hero-stats] wrote ${OUTPUT_PATH}`);
    },
    60 * 1000,
  );
});
